//! The console command table.
//!
//! One `CommandSpec` per verb: its name, the console capability it requires,
//! the group it lists under, and its help line. `dispatch` looks a command up
//! here and refuses it before running anything if the capability is not held,
//! so `help` and the permission check read from the same source of truth.
//!
//! The handler is still a match arm in `dispatch` rather than a field here.
//! Making it a field is the last item W11 asked for and is a separate change:
//! it needs one uniform handler signature, and the arms currently take four
//! different shapes.

use crate::cap;

pub(crate) struct CommandSpec {
    pub(crate) name: &'static str,
    pub(crate) cap: u32,
    pub(crate) cap_name: &'static str,
    pub(crate) group: &'static str,
    pub(crate) help: &'static str,
}

pub(crate) const COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        name: "help",
        cap: 0,
        cap_name: "-",
        group: "Inspect",
        help: "list commands or show help <command>",
    },
    CommandSpec {
        name: "version",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "show kernel and review-kit version",
    },
    CommandSpec {
        name: "about",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "show the Dezh OS thesis in one screen",
    },
    CommandSpec {
        name: "clear",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "clear the terminal",
    },
    CommandSpec {
        name: "explain",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "explain command authority and service path",
    },
    CommandSpec {
        name: "caps",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "show the console's capabilities",
    },
    CommandSpec {
        name: "mem",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "show the memory map",
    },
    CommandSpec {
        name: "frames",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "frame allocator self-test (alloc/zero/free)",
    },
    CommandSpec {
        name: "memstat",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "show frame ownership and process memory accounting",
    },
    CommandSpec {
        name: "ipcstat",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "show IPC send/receive/timeout counters",
    },
    CommandSpec {
        name: "ipc-typed-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "exercise typed IPC OK/BAD_REQUEST/TIMEOUT/DENIED",
    },
    CommandSpec {
        name: "status",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "show boot/runtime/storage summary",
    },
    CommandSpec {
        name: "tasks",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "show task slots and service bindings",
    },
    CommandSpec {
        name: "disk",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Services",
        help: "probe virtio-mmio slots for a block device",
    },
    CommandSpec {
        name: "agent",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "run a Dezh-IR agent program (capability-gated interpreter)",
    },
    CommandSpec {
        name: "bwrite",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Storage",
        help: "write a marker to disk sector 0 (virtio-blk)",
    },
    CommandSpec {
        name: "bread",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Storage",
        help: "read disk sector 0 (proves persistence)",
    },
    CommandSpec {
        name: "pset",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Storage",
        help: "durable Cairn: set current value (persisted) <text>",
    },
    CommandSpec {
        name: "pget",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Storage",
        help: "durable Cairn: read current value",
    },
    CommandSpec {
        name: "prollback",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Storage",
        help: "durable Cairn: roll back to previous value",
    },
    CommandSpec {
        name: "write",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Storage",
        help: "alias: write <text> to durable Cairn current value",
    },
    CommandSpec {
        name: "read",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Storage",
        help: "alias: read durable Cairn current value",
    },
    CommandSpec {
        name: "rollback",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Storage",
        help: "alias: roll back durable Cairn current value",
    },
    CommandSpec {
        name: "history",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Storage",
        help: "show v0 current/previous Cairn sector status",
    },
    CommandSpec {
        name: "cairn-status",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Storage",
        help: "Cairn v1: show namespaces, head refs, and commit slots",
    },
    CommandSpec {
        name: "cairn-commit",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Storage",
        help: "Cairn v1: commit a value <ns> <text> (namespace-capability gated)",
    },
    CommandSpec {
        name: "cairn-get",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Storage",
        help: "Cairn v1: read the head value of <ns>",
    },
    CommandSpec {
        name: "cairn-log",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Storage",
        help: "Cairn v1: show the commit chain of <ns> (newest first)",
    },
    CommandSpec {
        name: "cairn-rollback",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Storage",
        help: "Cairn v1: move the <ns> head ref back [n] commits (history kept)",
    },
    CommandSpec {
        name: "cairn-verify",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Storage",
        help: "Cairn v1: re-hash the head object of <ns> against its commit record",
    },
    CommandSpec {
        name: "cairn-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "F2 flagship: commits, log, bad write, rollback, verify, namespace denial",
    },
    CommandSpec {
        name: "root",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Storage",
        help: "show installed root marker and metadata",
    },
    CommandSpec {
        name: "install",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Install",
        help: "installer v1: plan|check|run|verify|report|rollback|--dry-run",
    },
    CommandSpec {
        name: "pkg-recv",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Packages",
        help: "receive a .dzp package over the UART (base64 lines, '.' ends)",
    },
    CommandSpec {
        name: "sig-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Packages",
        help: "package signing: verify a signed pkg, attenuate to the publisher ceiling, refuse tampered/revoked",
    },
    CommandSpec {
        name: "pkg-list",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Packages",
        help: "list packages installed via pkg-recv",
    },
    CommandSpec {
        name: "pkg-info",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Packages",
        help: "show a package's manifest grants (granted/denied)",
    },
    CommandSpec {
        name: "pkg-run",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Packages",
        help: "run an installed package with exactly its installed grants",
    },
    CommandSpec {
        name: "intent-open",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Intent",
        help: "open an Ahd (intent): a capability ceiling. intent-open <kind> [lease]",
    },
    CommandSpec {
        name: "intent-revoke",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Intent",
        help: "revoke an intent: it authorizes nothing further (provenance survives). intent-revoke <id>",
    },
    CommandSpec {
        name: "lease-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Intent",
        help: "self-contained proof: a leased intent expires after N runs; a revoked one authorizes nothing",
    },
    CommandSpec {
        name: "cap-demo",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Intent",
        help: "object-capability primitive: attenuated delegation + per-object generation-stamped revocation",
    },
    CommandSpec {
        name: "smp-demo",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "SMP: secondary harts brought up via SBI HSM run a parallel round with coherent atomics",
    },
    CommandSpec {
        name: "smp-task",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "SMP: dispatch a real U-mode task onto a secondary hart while the boot hart stays on the console",
    },
    CommandSpec {
        name: "smp-preempt",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "SMP: a secondary hart's OWN timer interrupts a U-mode task running there, and the task resumes",
    },
    CommandSpec {
        name: "smp-sched",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "SMP: symmetric scheduling - one task queue, every hart pulls from it, several U-mode tasks at once",
    },
    CommandSpec {
        name: "smp-isolate",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "SMP: concurrent tasks on different harts cannot reach each other's memory (per-task address spaces)",
    },
    CommandSpec {
        name: "ns-revoke",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Intent",
        help: "revoke a namespace capability at runtime (ocap generation bump). ns-revoke <ns>",
    },
    CommandSpec {
        name: "ns-grant",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Intent",
        help: "re-mint a namespace capability at the current generation. ns-grant <ns>",
    },
    CommandSpec {
        name: "nsrevoke-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Intent",
        help: "proof: revoke a live namespace capability at runtime; the storage path refuses until re-granted",
    },
    CommandSpec {
        name: "agentrevoke-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Intent",
        help: "the ocap namespace gate covers the untrusted AGENT path: a revoked ns refuses the agent's write",
    },
    CommandSpec {
        name: "marz-send",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "Marz: transmit one real frame to an authorized destination. marz-send <dest>",
    },
    CommandSpec {
        name: "marz-effect",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "Marz: a REAL external effect via the host gateway, recorded compensatable. marz-effect <dest> <verb> <arg>",
    },
    CommandSpec {
        name: "marz-ping",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "Marz: probe an authorized destination and RECEIVE the answer (ARP + ICMP echo). marz-ping <dest>",
    },
    CommandSpec {
        name: "dev-revoke",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Intent",
        help: "revoke a device capability at runtime (ocap generation). dev-revoke <block|net>",
    },
    CommandSpec {
        name: "dev-grant",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Intent",
        help: "re-mint a device capability. dev-grant <block|net>",
    },
    CommandSpec {
        name: "dev-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Intent",
        help: "device authority as a revocable ocap handle, above the per-destination gate",
    },
    CommandSpec {
        name: "marz-grant",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "grant egress authority for one destination. marz-grant <dest>",
    },
    CommandSpec {
        name: "marz-revoke",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "revoke egress authority for one destination (others untouched). marz-revoke <dest>",
    },
    CommandSpec {
        name: "marz-effect-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "Marz M3: a real send recorded as an irreversible effect that rollback refuses",
    },
    CommandSpec {
        name: "marz-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "Marz M2: per-destination egress authority + the DIFC export rule, proven on the wire",
    },
    CommandSpec {
        name: "irq-stat",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Inspect",
        help: "external device interrupts serviced via the PLIC",
    },
    CommandSpec {
        name: "net-probe",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Effects",
        help: "Marz M1: report the virtio-net device the egress boundary will be built on",
    },
    CommandSpec {
        name: "exfil-demo",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Effects",
        help: "confidentiality (DIFC): reading a secret taints an agent so it cannot leak it to a public sink",
    },
    CommandSpec {
        name: "taintflow-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "DIFC enforced on the storage path: read vault, then a write-down to a public ns is refused until declassify",
    },
    CommandSpec {
        name: "taint",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Effects",
        help: "show the operator's current secrecy taint (DIFC)",
    },
    CommandSpec {
        name: "declassify",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "privileged declassification: clear the operator's DIFC taint",
    },
    CommandSpec {
        name: "endorse",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "privileged endorsement (the dual of declassify): restore integrity after validating outside input",
    },
    CommandSpec {
        name: "ingress-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "proof: data read from the network is unvalidated and cannot become trusted state without an explicit endorsement",
    },
    CommandSpec {
        name: "intent-list",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Intent",
        help: "list open Ahds (intent tokens) with lease + revocation status",
    },
    CommandSpec {
        name: "intent-run",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Intent",
        help: "run a package under an Ahd; derived cap <= Ahd. intent-run <id> <app>",
    },
    CommandSpec {
        name: "intent-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Intent",
        help: "self-contained proof: same agent under two Ahds (in-intent vs beyond-intent)",
    },
    CommandSpec {
        name: "sand-log",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Effects",
        help: "Sand effect ledger for <ns>: actor -> intent -> derived cap -> reversibility",
    },
    CommandSpec {
        name: "sand-info",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Effects",
        help: "Sand: full provenance of the head effect in <ns>",
    },
    CommandSpec {
        name: "sand-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "W8 P2 flagship: run an agent under an intent, then show its effect on the ledger",
    },
    CommandSpec {
        name: "sfar-plan",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Effects",
        help: "rollback forecast for mission <ahd>: what could be undone, and with what confidence",
    },
    CommandSpec {
        name: "sfar-rollback",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "roll a whole mission <ahd> back: retract reversible effects, refuse the rest w/ reason",
    },
    CommandSpec {
        name: "sfar-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "W8 P3 flagship: an agent mission with a mix of effect classes, forecast, then honest rollback",
    },
    CommandSpec {
        name: "sfar-cross-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "W8 P3: a mission spanning two namespaces; rollback needs authority over every one it touched",
    },
    CommandSpec {
        name: "comp-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "W8 P3: roll back a compensatable effect by running + recording its registered compensating action",
    },
    CommandSpec {
        name: "redteam",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "W8 P4: a malicious agent tries five escapes; each is stopped at a named boundary and the system survives",
    },
    CommandSpec {
        name: "why-denied",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Effects",
        help: "W8 P5: explain the last denial (or `why-denied all`) and name the boundary that produced it",
    },
    CommandSpec {
        name: "tbar",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Effects",
        help: "W8 P5: the actor -> intent -> effect provenance graph for intent <ahd>",
    },
    CommandSpec {
        name: "overnight",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Effects",
        help: "W8 P7 flagship: leave a coding agent loose overnight, then account for and undo its night",
    },
    CommandSpec {
        name: "pkg-remove",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Packages",
        help: "remove an installed package (its grants go with it)",
    },
    CommandSpec {
        name: "pkg-store",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Packages",
        help: "inspect persistent package-store slots and blob range",
    },
    CommandSpec {
        name: "pkg-journal",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Packages",
        help: "inspect the package transaction journal",
    },
    CommandSpec {
        name: "pkg-recover",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Packages",
        help: "recover or quarantine an interrupted package transaction",
    },
    CommandSpec {
        name: "pkg-verify",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Packages",
        help: "verify one package's registry entry and persisted blob",
    },
    CommandSpec {
        name: "pkg-fault",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Packages",
        help: "inject a package transaction fault for reboot recovery tests",
    },
    CommandSpec {
        name: "pkg-gc",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Packages",
        help: "explicitly wipe blobs for logically removed package slots",
    },
    CommandSpec {
        name: "pkg-update",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Packages",
        help: "upload and transactionally update an Active package",
    },
    CommandSpec {
        name: "pkg-rollback",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Packages",
        help: "restore a verified previous package checkpoint",
    },
    CommandSpec {
        name: "pkg-versions",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Packages",
        help: "show active and previous package versions",
    },
    CommandSpec {
        name: "pkg-review",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Packages",
        help: "review package caps, pin state, and lifecycle policy",
    },
    CommandSpec {
        name: "pkg-pin",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Packages",
        help: "pin a package against surprise update/rollback",
    },
    CommandSpec {
        name: "pkg-unpin",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Packages",
        help: "remove a package pin after explicit review",
    },
    CommandSpec {
        name: "pkg-retire",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Packages",
        help: "logically retire a package; physical cleanup remains explicit",
    },
    CommandSpec {
        name: "pkg-lifecycle",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Packages",
        help: "summarize package lifecycle counts and policy",
    },
    CommandSpec {
        name: "pkg-audit",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Packages",
        help: "show where package lifecycle audit evidence is recorded",
    },
    CommandSpec {
        name: "apps",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Apps",
        help: "list app bundles or registry state (available|installed)",
    },
    CommandSpec {
        name: "app-info",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Apps",
        help: "show app bundle and install state",
    },
    CommandSpec {
        name: "app-install",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Apps",
        help: "transactionally install an available app",
    },
    CommandSpec {
        name: "app-run",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Apps",
        help: "run an installed app with registry-scoped caps",
    },
    CommandSpec {
        name: "app-remove",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Apps",
        help: "logically remove an installed app",
    },
    CommandSpec {
        name: "app-deny",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Apps",
        help: "prove installed app has no direct device/block grants",
    },
    CommandSpec {
        name: "app-permissions",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Apps",
        help: "show requested/granted/denied app authorities",
    },
    CommandSpec {
        name: "note-set",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Apps",
        help: "set dezh-note private value via app registry storage",
    },
    CommandSpec {
        name: "note-get",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Apps",
        help: "read dezh-note private value via app registry storage",
    },
    CommandSpec {
        name: "lab-set",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Apps",
        help: "set dezh-lab private value via app registry storage",
    },
    CommandSpec {
        name: "lab-get",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Apps",
        help: "read dezh-lab private value via app registry storage",
    },
    CommandSpec {
        name: "calc",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Apps",
        help: "run dezh-calc: calc <n> <+|-|*|/> <n>",
    },
    CommandSpec {
        name: "calc-history",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Apps",
        help: "read dezh-calc last stored result",
    },
    CommandSpec {
        name: "vault-put",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Apps",
        help: "store a private value through dezh-vault",
    },
    CommandSpec {
        name: "vault-get",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Apps",
        help: "read dezh-vault private value",
    },
    CommandSpec {
        name: "vblkd",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Services",
        help: "run long-lived user-space virtio-blk daemon + IPC client",
    },
    CommandSpec {
        name: "services",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Services",
        help: "list runtime services",
    },
    CommandSpec {
        name: "svc-stop",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Services",
        help: "stop a supervised service",
    },
    CommandSpec {
        name: "svc-restart",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Services",
        help: "restart a stopped/faulted service",
    },
    CommandSpec {
        name: "svc-fault-demo",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Services",
        help: "fault a supervised service and keep console alive",
    },
    CommandSpec {
        name: "install-check",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Services",
        help: "validate install manifest and disk root marker",
    },
    CommandSpec {
        name: "install-init",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Services",
        help: "initialize Dezh root marker/metadata on disk",
    },
    CommandSpec {
        name: "root-status",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Services",
        help: "read Dezh root metadata from disk",
    },
    CommandSpec {
        name: "events",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Audit",
        help: "show kernel/app/service event timeline",
    },
    CommandSpec {
        name: "audit",
        cap: cap::INSPECT,
        cap_name: "INSPECT",
        group: "Audit",
        help: "show audit summary and recent events",
    },
    CommandSpec {
        name: "uptime",
        cap: cap::TIME,
        cap_name: "TIME",
        group: "Inspect",
        help: "show timer uptime",
    },
    CommandSpec {
        name: "echo",
        cap: cap::ECHO,
        cap_name: "ECHO",
        group: "Demos",
        help: "echo <text>",
    },
    CommandSpec {
        name: "run",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "run a capability-limited U-mode task",
    },
    CommandSpec {
        name: "load",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "load a separate program into its own address space",
    },
    CommandSpec {
        name: "procs",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "run two separate programs concurrently (own address spaces)",
    },
    CommandSpec {
        name: "rogue",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Safety",
        help: "run a task that tries forbidden memory (gets killed)",
    },
    CommandSpec {
        name: "multi",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "run 3 cooperative U-mode tasks (round-robin)",
    },
    CommandSpec {
        name: "spy",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Safety",
        help: "prove a task cannot read another task's memory",
    },
    CommandSpec {
        name: "preempt",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "two non-yielding tasks interleave via timer preemption",
    },
    CommandSpec {
        name: "linux",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "run a Linux-ABI app via the Pol personality",
    },
    CommandSpec {
        name: "linux-elf",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "load a REAL static Linux/RISC-V ELF (F4); denied without PRINT",
    },
    CommandSpec {
        name: "bench",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "measure ecall round-trip cost (U-mode task)",
    },
    CommandSpec {
        name: "bench-pol",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "measure Pol Linux-ABI translation overhead vs the native path (F4)",
    },
    CommandSpec {
        name: "bench-os",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "benchmark syscall/trap boundary using a separate U-mode ELF",
    },
    CommandSpec {
        name: "bench-ipc",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "benchmark U-mode IPC service/client message flow",
    },
    CommandSpec {
        name: "bench-storage",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "validate storage through the registered virtio-block daemon",
    },
    CommandSpec {
        name: "bench-caps",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Safety",
        help: "validate denied capability/device paths",
    },
    CommandSpec {
        name: "bench-all",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "run the Dezh benchmark/validation suite v0",
    },
    CommandSpec {
        name: "stress-lab",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "run lab repeatedly and check frame reclamation",
    },
    CommandSpec {
        name: "ipc",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "agent delegates a capability to a service via IPC",
    },
    CommandSpec {
        name: "ipcq",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "two clients enqueue IPC messages without overwriting",
    },
    CommandSpec {
        name: "queues",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "alias: run IPC FIFO queue demo",
    },
    CommandSpec {
        name: "cairn",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Demos",
        help: "agent does a rollbackable action via a Cairn store service",
    },
    CommandSpec {
        name: "deny",
        cap: cap::SPAWN,
        cap_name: "SPAWN",
        group: "Safety",
        help: "run a compact denial tour",
    },
    CommandSpec {
        name: "secret",
        cap: cap::SECRET,
        cap_name: "SECRET",
        group: "Safety",
        help: "(needs a cap the console lacks)",
    },
    CommandSpec {
        name: "halt",
        cap: cap::HALT,
        cap_name: "HALT",
        group: "Power",
        help: "power off the machine",
    },
];
