//! Build script for the kernel:
//!  1. apply our kernel linker script so .text lands where OpenSBI jumps
//!     (0x8020_0000 on the QEMU `virt` board);
//!  2. compile separate user programs to their own riscv ELFs and stage them in
//!     OUT_DIR so the kernel can embed and load them.

use std::{env, fs, path::PathBuf, process::Command};

fn main() {
    println!("cargo:rustc-link-arg=-Tlinker.ld");
    println!("cargo:rerun-if-changed=linker.ld");

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    build_user_elf(&manifest, "userprog", "userprog");
    build_user_elf(&manifest, "virtio-blk", "virtio-blk");
    build_user_elf(&manifest, "bench-app", "dezh-bench");
    build_user_elf(&manifest, "note-app", "dezh-note");
    build_user_elf(&manifest, "lab-app", "dezh-lab");
    build_user_elf(&manifest, "calc-app", "dezh-calc");
    build_user_elf(&manifest, "vault-app", "dezh-vault");
    // A real Linux/RISC-V target ELF (Pol demo, F4) — built for the standard
    // musl Linux triple, not our bare-metal target.
    build_user_elf_for(
        &manifest,
        "linux-guest",
        "linux-guest",
        "riscv64gc-unknown-linux-musl",
    );

    build_signed_demo();
}

/// Sign a demo package at build time with the audited Ed25519 crate and a fixed
/// seed (deterministic → reproducible bytes), and emit the signer public key +
/// the signed DZSP envelope as Rust source the kernel embeds for `sig-demo`.
/// The kernel only *verifies*; no private key ever lives in the kernel.
fn build_signed_demo() {
    use dezh_core::{dzp, ir, sig};
    use ed25519_compact::{KeyPair, Seed};

    // Deterministic publisher key: fixed seed → fixed key → deterministic
    // signature (Ed25519 signing is deterministic), so the embedded bytes are
    // reproducible across builds.
    let kp = KeyPair::from_seed(Seed::new([0x42u8; 32]));
    let mut pk = [0u8; 32];
    pk.copy_from_slice(kp.pk.as_ref());

    // The demo requests print + cairn-read + cairn-write + IPC. The demo
    // publisher key's trust-store ceiling (in the kernel) is writer-only
    // (print + cairn), so IPC is dropped by publisher attenuation at install.
    let manifest =
        "name = \"signed-demo\"\nversion = \"1.0.0\"\ncaps = [\"print\", \"cairn-read\", \"cairn-write\", \"ipc\"]\n";
    let mut irbuf = [0u8; 1024];
    let payload = ir::demo_cairn(&mut irbuf);

    let mut inner = vec![0u8; dzp::HEADER_LEN + manifest.len() + payload.len()];
    let inner_len = dzp::pack(dzp::KIND_DEZH_IR, manifest, payload, &mut inner);
    let inner = &inner[..inner_len];

    let counter: u64 = 1;
    let mut ctx = [0u8; sig::SIG_CONTEXT_LEN];
    let cn = sig::signed_context(&mut ctx, counter).unwrap();
    let mut msg = inner.to_vec();
    msg.extend_from_slice(&ctx[..cn]);
    let signature = kp.sk.sign(&msg, None);
    let mut sig_bytes = [0u8; 64];
    sig_bytes.copy_from_slice(signature.as_ref());

    let mut env = vec![0u8; sig::ENV_HEADER_LEN + inner.len()];
    let en = sig::pack_envelope(&mut env, &pk, &sig_bytes, counter, inner).unwrap();
    let env = &env[..en];

    let mut src = String::from("// Generated by build.rs — do not edit.\n");
    src.push_str("pub const DEMO_SIGNER_PK: [u8; 32] = [");
    for b in pk {
        src.push_str(&format!("{b},"));
    }
    src.push_str("];\n");
    src.push_str(&format!(
        "pub const DEMO_SIGNED_PKG: &[u8; {}] = &[",
        env.len()
    ));
    for b in env {
        src.push_str(&format!("{b},"));
    }
    src.push_str("];\n");

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("signed_demo.rs");
    fs::write(&out, src).unwrap_or_else(|e| panic!("write signed_demo.rs: {e}"));
}

fn build_user_elf(manifest: &PathBuf, dir: &str, bin: &str) {
    build_user_elf_for(manifest, dir, bin, "riscv64gc-unknown-none-elf");
}

fn build_user_elf_for(manifest: &PathBuf, dir: &str, bin: &str, target: &str) {
    let prog = manifest.join(dir);
    println!("cargo:rerun-if-changed={}", prog.join("src/main.rs").display());
    println!("cargo:rerun-if-changed={}", prog.join("linker.ld").display());
    println!("cargo:rerun-if-changed={}", prog.join("Cargo.toml").display());
    println!("cargo:rerun-if-changed={}", prog.join(".cargo/config.toml").display());

    let cargo = env::var("CARGO").unwrap_or_else(|_| "cargo".into());
    let status = Command::new(&cargo)
        .current_dir(&prog)
        .args(["build", "--release"])
        .env_remove("RUSTFLAGS")
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        .env_remove("CARGO_TARGET_DIR")
        .env_remove("RUSTC_WORKSPACE_WRAPPER")
        .env_remove("RUSTC_WRAPPER")
        .status()
        .unwrap_or_else(|e| panic!("failed to spawn cargo for {dir}: {e}"));
    assert!(status.success(), "{dir} build failed");

    let elf = prog.join(format!("target/{target}/release/{bin}"));
    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join(format!("{bin}.elf"));
    fs::copy(&elf, &out)
        .unwrap_or_else(|e| panic!("copy {} -> {}: {e}", elf.display(), out.display()));
}
